language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
      - gperf

before_script:
  - autoreconf -vfi

env:
  - CONFOPTS="--enable-asm-backed-coroutines"
  - CONFOPTS="--disable-asm-backed-coroutines"

script: 
  - ./configure "${CONFOPTS}" || { cat config.log; false; }
  - make clean all check distcheck || { cat test/test-suite.log; false; }

## whitelist
branches:
  only:
    - master
    - series/0.3

notifications:
  email:
    - devel@fresse.org
