language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
      - gperf

before_script:
  - autoreconf -vfi

env:
  - CONFOPTS="--enable-asm-backed-coroutines"
  - CONFOPTS="--disable-asm-backed-coroutines"

script: 
  - ./configure "${CONFOPTS}" || { cat config.log; false; }
  - make clean all check distcheck || { cat test/test-suite.log; false; }

## blacklist
branches:
  except:
    - gh-pages

notifications:
  email:
    - devel@fresse.org
